name: fetin
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  mask_text_input_formatter: ^2.0.0
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  firebase_database: ^11.3.6

  provider: ^6.0.0

  table_calendar: ^3.2.0
  syncfusion_flutter_charts: ^30.2.5
  
  # Novas dependências
  shared_preferences: ^2.2.2
  pdf: ^3.10.4
  path_provider: ^2.1.4
  permission_handler: ^11.0.1
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2
  logger: ^2.0.2+1
  firebase_storage: ^12.3.4
  share_plus: ^10.1.1

  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
