// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
  apiKey: 'AIzaSyDuGlHVNBLy0_5nja5GA5bTtfXQwjegEmo',
  appId: '1:121736151982:web:b1d3d20961a1cacf66fe3f',
  messagingSenderId: '121736151982',
  projectId: 'fetin-eq103',
  authDomain: 'fetin-eq103.firebaseapp.com',
  storageBucket: 'fetin-eq103.firebasestorage.app',
  measurementId: 'G-81S11TTLK0',
  databaseURL: 'https://fetin-eq103-default-rtdb.firebaseio.com', // ✅ adicionado
);


  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKoxFoWDkXuY__KGrI3hQoFlzHnnPNQbY',
    appId: '1:121736151982:android:00813251a651f7ff66fe3f',
    messagingSenderId: '121736151982',
    projectId: 'fetin-eq103',
    storageBucket: 'fetin-eq103.firebasestorage.app',
    databaseURL: 'https://fetin-eq103-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkds0hi0gi0FVC6YOwdVXGX89ScGM7NLE',
    appId: '1:121736151982:ios:d51d84ac1995da3f66fe3f',
    messagingSenderId: '121736151982',
    projectId: 'fetin-eq103',
    storageBucket: 'fetin-eq103.firebasestorage.app',
    iosBundleId: 'com.example.fetin',
    databaseURL: 'https://fetin-eq103-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkds0hi0gi0FVC6YOwdVXGX89ScGM7NLE',
    appId: '1:121736151982:ios:d51d84ac1995da3f66fe3f',
    messagingSenderId: '121736151982',
    projectId: 'fetin-eq103',
    storageBucket: 'fetin-eq103.firebasestorage.app',
    iosBundleId: 'com.example.fetin',
    databaseURL: 'https://fetin-eq103-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuGlHVNBLy0_5nja5GA5bTtfXQwjegEmo',
    appId: '1:121736151982:web:67651d021459bdf966fe3f',
    messagingSenderId: '121736151982',
    projectId: 'fetin-eq103',
    authDomain: 'fetin-eq103.firebaseapp.com',
    storageBucket: 'fetin-eq103.firebasestorage.app',
    measurementId: 'G-CBG4WB81RX',
    databaseURL: 'https://fetin-eq103-default-rtdb.firebaseio.com',
  );
}
